### ISSUE TITLE
Admin page not loading. Just blank white screen. No errors.

### ISSUE THREAD

**Issue by alexpeterson** [croogo/croogo#984]
I have migrated a Croogo site over to a new server. The front-end loads fine however the /admin page is just a blank white page. There are no errors to help debug which is really frustrating!

Has anyone experienced the same? Or do you have any idea why this might be??

**Comment by rchavik** [comment]
there are few things to check:
- turn debug on, then check logs/browser output
- check nginx or apache error logs, sometimes the error happens early and not logged in app's log

which versions were involved?

**Comment by alexpeterson** [comment]
turning debug on doesn't provide any output. 

I suspect it's something to do with prefix routing?

I can access the login screen at /admin/users/users/login but when I try and login I get -

Security Error - The requested address was not found on this server.

Versions are Croogo 2.3.2 (CakePHP 2.9)

I found this error in tmp/logs/error.log

`2020-11-18 11:01:57 Error: [MissingActionException] Action UsersController::admin_admin() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'admin_admin',
)
Request URL: /admin/users/users/admin
Stack Trace:
#0 /home/adminw/public_html/Vendor/croogo/croogo/Croogo/Controller/CroogoAppController.php(228): Controller->invokeAction(Object(CakeRequest))
#1 /home/adminw/public_html/Vendor/cakephp/cake29/lib/Cake/Routing/Dispatcher.php(193): CroogoAppController->invokeAction(Object(CakeRequest))
#2 /home/adminw/public_html/Vendor/cakephp/cake29/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#3 /home/adminw/public_html/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#4 {main}
`

**Comment by rchavik** [comment]
why is it going to /admin/users/users/admin ?

is the generated form action wrong?

**Comment by alexpeterson** [comment]
No idea why it's going to /admin/users/users/admin/ - I presume this was the full url. Maybe the rewrite is incorrect? Although I've not changed anything.

I think step 1 is to try and get the /admin /grasp pages loading and then I expect the login form will work.

Why would the /admin url bring up a white screen? (with not errors). It's bizarre.
